USED_MODELS = ['Baseline', 'SDBN', 'UBM', 'UBM-IA', 'EB_UBM', 'EB_UBM-IA', 'DCM', 'DCM-IA', 'DBN', 'DBN-IA']
EXTENDED_LOG_FORMAT = False

TRAIN_FOR_METRIC = False
PRINT_EBU_STATS = True

MAX_ITERATIONS = 30
DEBUG = False
PRETTY_LOG = True
MIN_DOCS_PER_QUERY = 10
MAX_DOCS_PER_QUERY = 10
SERP_SIZE = 10
TRANSFORM_LOG = False
QUERY_INDEPENDENT_PAGER = False
DEFAULT_REL = 0.5
MAX_VERTICAL_ID = 20
DEFAULT_SAT_CLICK = 0.5
DEFAULT_SAT_EXAM = 0.5
ALPHA_PRIOR = [1.0, 2.0]
BETA_PRIOR = [1.0, 2.0]
S_C_PRIOR = [1.0, 5.0]
S_E_PRIOR = [1.0, 5.0]
VPT_EPSILON = 1